name: Selenium with Login test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Build with Maven

      run: mvn -B clean test

  test_1:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Test with Maven

      run: mvn clean test
